name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            os: ubuntu-latest
            output_path: linux_so/
          - platform: windows
            os: windows-latest
            output_path: windows_dll/
          - platform: android
            os: ubuntu-latest
            output_path: |
                libXray.aar
                libXray-sources.jar
          - platform: apple
            os: macos-latest
            output_path: apple_xcframework
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Set up winget for Windows build
      if: matrix.platform == 'windows'
      uses: Cyberboss/install-winget@v1
      
    - name: Set up LLVM-MinGW for Windows build
      if: matrix.platform == 'windows'
      run: winget install MartinStorsjo.LLVM-MinGW.UCRT --disable-interactivity --accept-source-agreements

    - name: Build for Linux
      if: matrix.platform == 'linux'
      run: python3 build/main.py linux
      env:
        CGO_CFLAGS: "-D_GNU_SOURCE"

    - name: Build for Windows
      if: matrix.platform == 'windows'
      run: python build/main.py windows
    
    - name: Build for Android
      if: matrix.platform == 'android'
      run: python3 build/main.py android 21

    - name: Build for Apple (macOS/iOS/tvOS)
      if: matrix.platform == 'apple'
      run: python3 build/main.py apple go

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output-${{ matrix.platform }}
        path: ${{ matrix.output_path }}
  
