name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            os: ubuntu-latest
          - platform: windows
            os: ubuntu-latest
          - platform: android
            os: ubuntu-latest
          - platform: apple
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Build for Linux
      if: matrix.platform == 'linux'
      run: python3 build/main.py linux

    - name: Build for Windows
      if: matrix.platform == 'windows'
      run: python3 build/main.py windows

    - name: Build for Android
      if: matrix.platform == 'android'
      run: python3 build/main.py android 21

    - name: Build for Apple (macOS/iOS)
      if: matrix.platform == 'apple'
      run: python3 build/main.py apple go

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output-${{ matrix.platform }}
        path: build/output/
