name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            os: ubuntu-latest
            output_path: linux_so/
          - platform: windows
            os: ubuntu-latest
            output_path: windows_dll/
          - platform: android
            os: ubuntu-latest
            output_path: android/
          - platform: apple
            os: macos-latest
            output_path: apple_xcframework/
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24.4'

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
  
    - name: Install MinGW for Windows cross-compilation
      if: matrix.platform == 'windows'
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64

    - name: Build for Linux
      if: matrix.platform == 'linux'
      run: python3 build/main.py linux
      env:
        CGO_CFLAGS: "-D_GNU_SOURCE"

    - name: Build for Windows
      if: matrix.platform == 'windows'
      run: python3 build/main.py windows
      env:
        CC: x86_64-w64-mingw32-gcc
    
    - name: Build for Android
      if: matrix.platform == 'android'
      run: python3 build/main.py android 21

    - name: Build for Apple (macOS/iOS/tvOS)
      if: matrix.platform == 'apple'
      run: python3 build/main.py apple go

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output-${{ matrix.platform }}
        path: ${{ matrix.output_path }}
  
